### ISSUE TITLE
Edit the coded noun

### ISSUE THREAD

**Issue by manarlandis** [oudalab/fajita#134]
In Flagged Summary, I can edit most of the coders input but I need to be able to edit the word itself if there is a typo error.

**Comment by YanLiang1102** [comment]
@manarlandis  this should be fixed.

**Comment by manarlandis** [comment]
@yan I just tried it and I still can't edit it. (word) is the only data that I cant edit, which I need to fix some typo sometimes.

**Comment by YanLiang1102** [comment]
this is fixed
